project/urls.py
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin

from filebrowser_safe.settings import DIRECTORY as FILEBROWSER_DIRECTORY
from mezzanine.core.views import direct_to_template


admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

# Custom admin View On Site logic
urlpatterns = i18n_patterns("",
    url(r'^admin/r/(?P<content_type_id>\d+)/(?P<object_id>.+)/$',
        'translations.views.shortcut',
        name='view_on_site'),
)

urlpatterns += i18n_patterns("",
    (r'^', include('protected_assets.urls')),
    (r"^admin/", include(admin.site.urls)),
)

# Make rosetta avaiable
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )


# Protected downloads
urlpatterns += patterns("protected_assets.views",
    url(r"^%s%sprotected/(?P<path>.*)$" % (settings.MEDIA_URL.lstrip('/'), FILEBROWSER_DIRECTORY), "protected_download"),
)

# Serving media for local dev
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += patterns('',

    # Enable the set language view
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    url("^$", direct_to_template, {"template": "index.html"}, name="home"),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.

    # url("^$", "mezzanine.pages.views.page", {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.

    # url("^$", "mezzanine.blog.views.blog_post_list", name="home"),

    url("^snippets/", include("snippets.urls")),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!
    ("^", include("registration_salesforce.urls")),

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    ("^", include("mezzanine.urls")),

    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

)

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

protected_assets/models.py
from django.conf import settings
from django.db import models
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _


def _agreement_filename(instance, filename):
    """Custom upload location generator."""
    directory = 'uploads/agreements/{}/'.format(instance.language)
    return directory + now().strftime('%Y-%m-%d_%H:%M:%S_agreement.pdf')


class Agreement(models.Model):
    """Marketing agreement that users can sign."""
    name = models.CharField(
        max_length=255, default='Prototype Branding Agreement')
    version = models.CharField(max_length=20)
    created = models.DateTimeField(default=now, editable=False)
    language = models.CharField(
        max_length=10, choices=settings.LANGUAGES,
        default=settings.LANGUAGE_CODE)
    agreement_pdf = models.FileField(
        max_length=255, upload_to=_agreement_filename)
    translated_from = models.ForeignKey(
        'self', related_name='translations', blank=True, null=True,
        help_text=_('Translated from'))

    class Meta:
        unique_together = ('language', 'version')

    @property
    def url(self):
        return self.agreement_pdf.url

    def __unicode__(self):
        return self.name + ' ' + self.version


class SignedAgreement(models.Model):
    """Record of user signing the user agreement."""
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
        help_text=_('User which signed the agreement.'))
    timestamp = models.DateTimeField(default=now,
        help_text=_('Date and time the agreement was signed.'))
    ip = models.GenericIPAddressField(blank=True, null=True,
        help_text=_('IP address of the signing request.'))
    agreement = models.ForeignKey(
        Agreement, null=True,
        help_text=_('Version of the agreement which was signed.'))

    class Meta:
        ordering = ['-timestamp']
        unique_together = ('user', 'agreement')

sandstone/models.py
from django.contrib.auth.signals import user_logged_in
from django.dispatch import receiver
from django.db import models
from mezzanine.forms.models import Form
from mezzanine.pages.models import Page
from mezzanine.pages.models import RichTextPage
from mezzanine.pages.models import Link
from concurrency.api import apply_concurrency_check
from concurrency.fields import IntegerVersionField

from django.utils.translation import ugettext_lazy as _


apply_concurrency_check(Form, 'version', IntegerVersionField)
apply_concurrency_check(RichTextPage, 'version', IntegerVersionField)


@receiver(user_logged_in)
def add_just_logged_in_cookie(**kwargs):
    """Mark the request that a user logged in with."""
    kwargs['request'].just_logged_in = True

sandstone/views.py
from diff_match_patch import diff_match_patch

from concurrency.views import ConflictResponse

from django.template import loader
from django.template.context import RequestContext
from django.utils.safestring import mark_safe


def get_diff(current, stored):
    data = []
    dmp = diff_match_patch()
    fields = current._meta.fields
    for field in fields:
        v1 = getattr(current, field.name, "")
        v2 = getattr(stored, field.name, "")
        diff = dmp.diff_main(unicode(v1), unicode(v2))
        dmp.diff_cleanupSemantic(diff)
        html = dmp.diff_prettyHtml(diff)
        html = mark_safe(html)
        if len(diff) > 1:
            data.append((field, v1, v2, html))
    return data


def conflict(request, target=None, template_name='409.html'):
    template = loader.get_template(template_name)
    try:
        saved = target.__class__._default_manager.get(pk=target.pk)
        diff = get_diff(target, saved)
        target_url = target.__class__.get_admin_url(target)
    except target.__class__.DoesNotExists:
        saved = None
        diff = None
        target_url = None
    ctx = RequestContext(request, {'target': target,
                                   'diff': diff,
                                   'saved': saved,
                                   'target_url': target_url})
    return ConflictResponse(template.render(ctx))

sandstone/templates/409.html
{% extends "admin/base_site.html" %}

{% load concurrency i18n%}

{% block title %}{% trans "Editing Conflict Occurred" %}{% endblock %}

{% block content_title %}<h1>{% trans "Editing Conflict Occurred" %}</h1>{% endblock %}

{% block coltype %}flex{% endblock %}

{% block content %}
<div id="content-main">
    <div class="result-list-container">
        <p class="errornote">{% trans "Unable to save revision!!" %}</p>
        <p>{% trans "Another author has saved changes to this object while you were editing. This view provides the differences between versions. You will need to copy the changes you would like to keep and re-edit the object." %}</p>
        <p>{% trans "Fields with differences are presented for your review." %}</p>
        <div class="result-list">
            <table cellspacing="0">
                <thead>
                    <tr>
                        <th>{% trans "Field" %}</th>
                        <th>{% trans "Current" %}</th>
                        <th>{% trans "Stored" %}</th>
                        <th>{% trans "Diff" %}</th>
                    </tr>
                </thead>
                <tbody>
                {% for field, current, stored, entry in diff %}
                    {% if not field.primary_key and not field|is_version %}
                        <tr class="{% cycle 'row1' 'row2' %}">
                            <td>{{ field.verbose_name }}</td>
                            <td>{{ current }}</td>
                            <td>{{ stored }}</td>
                            <td>{{ entry }}</td>
                        </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
   </div>
    <div><a href="{{ target_url }}">{% trans "Edit" %}</a></div>
</div>
{% endblock %}

sandstone/templates/base.html
<!DOCTYPE html>
<html class="windows no-js" lang="{{ LANGUAGE_CODE }}"{% if LANGUAGE_BIDI %} dir="rtl"{% endif %} data-ga-code="{{ settings.GOOGLE_ANALYTICS_ID }}" {% block page_slug %}data-page-slug="{{ page.get_slug|default:"" }}"{% endblock %}>
{% load pages_tags mezzanine_tags i18n future staticfiles waffle_tags %}
    <head>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="keywords" content="{% block meta_keywords %}{% endblock %}">
        <meta name="description" content="{% block meta_description %}{% endblock %}">
        {% if request.session.ready_download %}
            <meta name="_download" content="{{ request.session.ready_download }}">
        {% endif %}
        <title>{% block meta_title %}{% endblock %} &mdash; {{ settings.SITE_TITLE }}</title>
        <link rel="shortcut icon" href="{% static "img/favicon.ico" %}">

        {% compress css %}
            {% if LANGUAGE_BIDI %}
                <link rel="stylesheet" href="{% static "css/rtl.css" %}">
            {% endif %}
        {% endcompress %}
        {% block extra_css %}{% endblock %}

        {% if debug %}
            <link rel="stylesheet/less" type="text/css" media="all" href="{% static "css/sandstone/sandstone-resp.less" %}" />
            <script src="{% static "js/libs/less-1.7.1.min.js" %}"></script>
        {% else %}
            {% compress css %}
                <link rel="stylesheet" type="text/less" href="{% static "css/sandstone/sandstone-resp.less" %}" media="screen" />
            {% endcompress %}
        {% endif %}
        <link href="//mozorg.cdn.mozilla.net/media/css/tabzilla-min.css" rel="stylesheet">
        {% compress js %}
            <script src="{% static "mezzanine/js/"|add:settings.JQUERY_FILENAME %}"></script>
            <script src="{% static "js/libs/cookie-monster.js" %}"></script>
            <script src="{% static "js/ga.js" %}"></script>
        {% endcompress %}
        {% block extra_js %}{% endblock %}
        <!--[if lt IE 8]>
        <script src="{% static "js/libs/html5shiv.js" %}"></script>
        <![endif]-->

        {% block extra_head %}{% endblock %}
    </head>
    <body id="sandstone" class="sky {% block extra-body-class %}{% endblock %}">
        {% nevercache %}
        {% if messages %}
        <div class="messages">
        {% for message in messages %}
        <div class="alert alert-dismissable alert-{{ message.tags }}" data-alert="alert">
            <a class="close" data-dismiss="alert" aria-hidden="true"><i class="fa fa-times-circle"></i></a>
            {{ message }}
        </div>
        {% endfor %}
        </div>
        {% endif %}
        {% endnevercache %}
        <div id="outer-wrapper">
            <div id="swoop-wrapper">
                <div id="wrapper">
                    <header id="masthead">
                      <a href="https://www.mozilla.org/" id="tabzilla">Mozilla</a>
                      <nav id="nav-main" role="navigation">
                        <span class="toggle" role="button" aria-controls="nav-main-menu" tabindex="0">Menu</span>
                        {% page_menu "pages/menus/dropdown.html" %}
                      </nav>
                        <div id="logo"><a href="{% url "home" %}"><img src="{% static "img/sandstone/firefox-logo.png" %}" alt="Firefox OS"></a></div>
                        {% block masthead-content %}
                           <article class="hero-column">
                              <h1>{{ title }}</h1>
                           </article>
                        {% endblock masthead-content %}
                    </header>
                </div>
            </div>
        </div>
        <div id="main-content">
            <div id="content-wrapper">
                <div class="container">
                    {% block sidebar %}
                        <aside id="sidebar">
                          <nav>
                            {% page_menu "pages/menus/tree.html" %}
                          </nav>
                        </aside>
                    {% endblock %}
                    {% block index %}{% endblock %}
                    <article class="main-column">
                    {% block main %}
                    {% endblock %}
                    </article>
                </div>
            </div>
        </div>

        {% block site_footer %}
        <footer id="colophon">
            <div class="row">

              <div class="footer-logo">
                <a href="https://www.mozilla.org"><img src="{% static "img/sandstone/footer-mozilla.png" %}" alt="mozilla"></a>
                {% flag 'language-switching' %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% if languages|length > 1 %}
                        <form action="{% url 'set_language' %}" method="post" id="language-form">{% csrf_token %}
                            <input name="next" type="hidden" value="{{ request.path }}" />
                            <label for="id_language">{% trans "Other languages" %}:</label>
                            <select id="id_language" name="language">
                            {% for language in languages %}
                            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
                                {{ language.name_local }} ({{ language.code }})
                            </option>
                            {% endfor %}
                            </select>
                        </form>
                    {% endif %}
                {% endflag %}
              </div>

              <div class="footer-license">
                    <p>{% blocktrans with current_year=current_date|date:"Y" web_url="https://www.mozilla.org/foundation/licensing/website-content.html" %}Portions of this content are &copy;1998–{{ current_year }} by individual
                    mozilla.org contributors. Content available under
                    a <a href={{ web_url }}>Creative Commons license</a>.{% endblocktrans %}<br><br>
                    <a href="https://www.mozilla.org/en-US/contribute/page/">{% trans "Contribute to this page" %}</a></p>
              </div>
              <ul class="footer-nav">
                <li><a href="https://www.mozilla.org/en-US/contact/spaces/">{% trans "Contact Us" %}</a></li>
                <li><a href="https://www.mozilla.org/en-US/about/partnerships/">{% trans "Partner with Us" %}</a></li>
                <li><a href="https://www.mozilla.org/en-US/privacy/">{% trans "Privacy Policy" %}</a></li>
                <li><a href="https://www.mozilla.org/about/legal.html">{% trans "Legal Notices" %}</a></li>
                <li><a href="https://www.mozilla.org/legal/fraud-report/index.html">{% trans "Report Trademark Abuse" %}</a></li>
              </ul>

              <ul class="footer-nav">
                <li><a href="https://twitter.com/mozilla">{% trans "Mozilla on Twitter" %}</a></li>
                <li><a href="https://twitter.com/firefox">{% trans "Firefox on Twitter" %}</a></li>
                <li><a href="https://facebook.com/mozilla">{% trans "Mozilla on Facebook" %}</a></li>
                <li><a href="https://facebook.com/Firefox">{% trans "Firefox on Facebook" %}</a></li>
                <li><a href="https://affiliates.mozilla.org/">{% trans "Firefox Affiliates" %}</a></li>
              </ul>

                </div>
            </footer>

            {% endblock %}


        {% include "includes/footer_scripts.html" %}
        {% block js %}
          {% compress js %}
            <script src="{% static "js/site.js" %}"></script>
            <script src="{% static "js/nav-main-resp.js" %}"></script>
          {% endcompress %}
            <script src="//mozorg.cdn.mozilla.net/tabzilla/tabzilla.js"></script>
        {% endblock %}
    </body>
</html>

sandstone/templates/index.html
{% extends "base.html" %}
{% load i18n staticfiles compress %}

{% block meta_title %}{% trans "Home" %}{% endblock %}
{% block title %}{% trans "Home" %}{% endblock %}
{% block page_slug %}data-page-slug="index"{% endblock %}

{% block extra-body-class %}index{% endblock %}

{% block extra_css %}
  <link rel="stylesheet" type="text/css" media="all" href="{% static "css/home.css" %}" />
{% endblock %}

{% block js %}
  {{ block.super }}
  {% compress js %}
    <script src="{% static "js/home.js" %}"></script>
  {% endcompress %}
{% endblock %}

{% block masthead-content %}
  <section class="home-intro">
    <h1>{% blocktrans %}Building the future<br>starts here{% endblocktrans %}</h1>
    <p class="intro-column">
      {% blocktrans %}
        Welcome to the world of Firefox OS. On this site, you’ll find everything you need to build, customize, and bring to market your own version of our groundbreaking mobile operating system. You’ll also learn how to use the Firefox OS brand on a phone, tablet or other device. <em>Get started below.</em>
      {% endblocktrans %}
    </p>
    <div class="roles">
      <label for="role-manufacturer" class="role-button">
        <input type="radio" name="role" id="role-manufacturer" value="manufacturer">
        {% trans "I'm a Manufacturer" %}
      </label>
      <label for="role-operator" class="role-button">
        <input type="radio" name="role" id="role-operator" value="operator">
        {% trans "I'm an Operator" %}
      </label>
    </div>
   </section>
 {% endblock %}

{% block sidebar %}{# exclude the sidebar #}{% endblock %}

{% block index %}
  <a class="guide-close">
    {% trans "Close" %}
    <i class="fa fa-times"></i>
  </a>

  <div id="manufacturer-guide" class="home-guide">
    <section class="home-guide-intro">
      <h2>{% trans "Say hello to Firefox OS" %}</h2>
      <p>
        {% blocktrans %}
          You already make great hardware — now it’s time to build and customize an amazing OS for it. Learn about the technology behind Firefox OS and how to bring a brand new Firefox OS phone to life.
        {% endblocktrans %}
      </p>
    </section>

    <section id="home-guide-learn" class="home-guide-section">
      <h3>{% trans "Learn" %}</h3>
      <p>
        {% blocktrans %}
          Explore Firefox OS and the Firefox Marketplace. Get localization support, roadmaps and a complete, detailed list of every feature.
        {% endblocktrans %}
      </p>
      <p><a href="/learn" class="cta">{% trans "Get started" %}</a></p>
    </section>

    <section id="home-guide-build" class="home-guide-section">
      <h3>{% trans "Build" %}</h3>
      <p>
        {% blocktrans %}
          Create and customize your own version of Firefox OS. Learn more about hardware requirements, supported chipsets, and how to contribute back to the community.
        {% endblocktrans %}
      </p>
      <p><a href="/build" class="cta">{% trans "Build today" %}</a></p>
    </section>

    <section id="home-guide-market" class="home-guide-section">
      <h3>{% trans "Market" %}</h3>
      <p>
        {% blocktrans %}
          Take your product to market. Get access and support to the essential licenses and Firefox OS brand assets you’ll need, quickly and easily.
        {% endblocktrans %}
      </p>
      <p><a href="/market" class="cta">{% trans "Begin the process" %}</a></p>
    </section>

    <section id="home-guide-maintain" class="home-guide-section">
      <h3>{% trans "Maintain" %}</h3>
      <p>
        {% blocktrans %}
          After you’ve launched your Firefox OS device, you’ll be able to get the information needed to deliver updates to customers, access our help desk and get reports.
        {% endblocktrans %}
      </p>
      <p><a href="/maintain" class="cta">{% trans "Begin the process" %}</a></p>
    </section>
  </div>

  <div id="operator-guide" class="home-guide">
    <section class="home-guide-intro">
      <h2>{% trans "Meet Firefox OS" %}</h2>
      <p>
        {% blocktrans %}
          Looking to bring something truly new to your customers? Discover why they’ll be just as excited about Firefox OS as we are. Here, you’ll get the ins and outs of the operating system, the phones and the brand.
        {% endblocktrans %}
      </p>
    </section>

    <section id="home-guide-learn" class="home-guide-section">
      <h3>{% trans "Learn" %}</h3>
      <p>
        {% blocktrans %}
          Explore Firefox OS and the Firefox Marketplace. Get localization support, roadmaps and a complete, detailed list of every feature.
        {% endblocktrans %}
      </p>
      <p><a href="/learn" class="cta">{% trans "Get started" %}</a></p>
    </section>

    <section id="home-guide-build" class="home-guide-section">
      <h3>{% trans "Build" %}</h3>
      <p>
        {% blocktrans %}
          Customize your own version of Firefox OS. Learn more about hardware requirements, connect with manufactures making Firefox OS devices, and discover how you can to contribute back to the Firefox OS community.
        {% endblocktrans %}
      </p>
      <p><a href="/build" class="cta">{% trans "Build today" %}</a></p>
    </section>

    <section id="home-guide-market" class="home-guide-section">
      <h3>{% trans "Market" %}</h3>
      <p>
        {% blocktrans %}
          Take your product to market. Get access and support to the essential licenses and Firefox OS brand assets you’ll need, quickly and easily.
        {% endblocktrans %}
      </p>
      <p><a href="/market" class="cta">{% trans "Begin the process" %}</a></p>
    </section>

    <section id="home-guide-maintain" class="home-guide-section">
      <h3>{% trans "Maintain" %}</h3>
      <p>
        {% blocktrans %}
          After you’ve launched your Firefox OS device, you’ll be able to get the information needed to deliver updates to customers, access our help desk and get reports.
        {% endblocktrans %}
      </p>
      <p><a href="/maintain" class="cta">{% trans "Begin the process" %}</a></p>
    </section>
  </div>
{% endblock %}

{% block main %}{%endblock %}