project/urls.py
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin

from filebrowser_safe.settings import DIRECTORY as FILEBROWSER_DIRECTORY
from mezzanine.core.views import direct_to_template


admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

# Custom admin View On Site logic
urlpatterns = i18n_patterns("",
    url(r'^admin/r/(?P<content_type_id>\d+)/(?P<object_id>.+)/$',
        'translations.views.shortcut',
        name='view_on_site'),
)

urlpatterns += i18n_patterns("",
    (r'^', include('protected_assets.urls')),
    (r"^admin/", include(admin.site.urls)),
)

# Make rosetta avaiable
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )


# Protected downloads
urlpatterns += patterns("protected_assets.views",
    url(r"^%s%sprotected/(?P<path>.*)$" % (settings.MEDIA_URL.lstrip('/'), FILEBROWSER_DIRECTORY), "protected_download"),
)

# Serving media for local dev
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += patterns('',

    # Enable the set language view
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    url("^$", direct_to_template, {"template": "index.html"}, name="home"),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.

    # url("^$", "mezzanine.pages.views.page", {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.

    # url("^$", "mezzanine.blog.views.blog_post_list", name="home"),

    url("^snippets/", include("snippets.urls")),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!
    ("^", include("registration_salesforce.urls")),

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    ("^", include("mezzanine.urls")),

    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

)

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

protected_assets/models.py
from django.conf import settings
from django.db import models
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _


def _agreement_filename(instance, filename):
    """Custom upload location generator."""
    directory = 'uploads/agreements/{}/'.format(instance.language)
    return directory + now().strftime('%Y-%m-%d_%H:%M:%S_agreement.pdf')


class Agreement(models.Model):
    """Marketing agreement that users can sign."""
    name = models.CharField(
        max_length=255, default='Prototype Branding Agreement')
    version = models.CharField(max_length=20)
    created = models.DateTimeField(default=now, editable=False)
    language = models.CharField(
        max_length=10, choices=settings.LANGUAGES,
        default=settings.LANGUAGE_CODE)
    agreement_pdf = models.FileField(
        max_length=255, upload_to=_agreement_filename)
    translated_from = models.ForeignKey(
        'self', related_name='translations', blank=True, null=True,
        help_text=_('Translated from'))

    class Meta:
        unique_together = ('language', 'version')

    @property
    def url(self):
        return self.agreement_pdf.url

    def __unicode__(self):
        return self.name + ' ' + self.version


class SignedAgreement(models.Model):
    """Record of user signing the user agreement."""
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
        help_text=_('User which signed the agreement.'))
    timestamp = models.DateTimeField(default=now,
        help_text=_('Date and time the agreement was signed.'))
    ip = models.GenericIPAddressField(blank=True, null=True,
        help_text=_('IP address of the signing request.'))
    agreement = models.ForeignKey(
        Agreement, null=True,
        help_text=_('Version of the agreement which was signed.'))

    class Meta:
        ordering = ['-timestamp']
        unique_together = ('user', 'agreement')

sandstone/models.py
from django.contrib.auth.signals import user_logged_in
from django.dispatch import receiver
from django.db import models
from mezzanine.forms.models import Form
from mezzanine.pages.models import Page
from mezzanine.pages.models import RichTextPage
from mezzanine.pages.models import Link
from concurrency.api import apply_concurrency_check
from concurrency.fields import IntegerVersionField

from django.utils.translation import ugettext_lazy as _


apply_concurrency_check(Form, 'version', IntegerVersionField)
apply_concurrency_check(RichTextPage, 'version', IntegerVersionField)


@receiver(user_logged_in)
def add_just_logged_in_cookie(**kwargs):
    """Mark the request that a user logged in with."""
    kwargs['request'].just_logged_in = True

sandstone/views.py
from diff_match_patch import diff_match_patch

from concurrency.views import ConflictResponse

from django.template import loader
from django.template.context import RequestContext
from django.utils.safestring import mark_safe


def get_diff(current, stored):
    data = []
    dmp = diff_match_patch()
    fields = current._meta.fields
    for field in fields:
        v1 = getattr(current, field.name, "")
        v2 = getattr(stored, field.name, "")
        diff = dmp.diff_main(unicode(v1), unicode(v2))
        dmp.diff_cleanupSemantic(diff)
        html = dmp.diff_prettyHtml(diff)
        html = mark_safe(html)
        if len(diff) > 1:
            data.append((field, v1, v2, html))
    return data


def conflict(request, target=None, template_name='409.html'):
    template = loader.get_template(template_name)
    try:
        saved = target.__class__._default_manager.get(pk=target.pk)
        diff = get_diff(target, saved)
        target_url = target.__class__.get_admin_url(target)
    except target.__class__.DoesNotExists:
        saved = None
        diff = None
        target_url = None
    ctx = RequestContext(request, {'target': target,
                                   'diff': diff,
                                   'saved': saved,
                                   'target_url': target_url})
    return ConflictResponse(template.render(ctx))

sandstone/templates/accounts/account_login.html
{% extends "accounts/account_form.html" %}
{% load i18n future %}

{% block main %}

{% if request.user.is_authenticated %}
    <p>{% trans "You're already logged in. If you'd like to log in as a different user, you'll need to log out first." %}</p>
{% else %}
    {{ block.super }}
    {% url "signup" as signup_url %}
    <p>{% blocktrans with request.GET.next as next %}If you don't have an account you can <a href="{{ signup_url }}?next={{ next }}">sign up</a> for one now.{% endblocktrans %}</p>
    {% url "mezzanine_password_reset" as password_reset_url %}
    {% url "profile_update" as profile_update_url %}
    {% blocktrans %}<p>You can also <a href="{{ password_reset_url }}?next={{ profile_update_url }}">reset your password</a> if you've forgotten it.</p>{% endblocktrans %}</p>
{% endif %}

{% endblock %}

{% block account_form_actions %}
    <button class="primary button button-blue arrow" type="submit" value="{{ title }}"><span>{% trans "Sign In" %}</span></button>
{% endblock %}

sandstone/templates/accounts/account_password_reset.html
{% extends "accounts/account_form.html" %}
{% load i18n %}

{% block main %}
{{ block.super }}
<p>{% trans "Enter your email address and you'll receive an email with a link you need to click, in order to log in and change your password." %}</p>
{% endblock %}

{% block account_form_actions %}
    <button class="primary button button-blue arrow" type="submit" value="{{ title }}"><span>{% trans "Password Reset" %}</span></button>
{% endblock %}

sandstone/templates/accounts/account_profile_update.html
{% extends "accounts/account_form.html" %}
{% load i18n %}

{% block account_form_actions %}
    <button class="primary button button-blue arrow" type="submit" value="{{ title }}"><span>{% trans "Update Profile" %}</span></button>
{% endblock %}

{% block main %}
  {{ block.super }}

  {% if user.signedagreement_set.all %}
    <h2>{% trans "Signed Agreements" %}</h2>
    <table class="table">
      <thead>
        <tr>
          <th>{% trans "Name" %}</th>
          <th>{% trans "Version" %}</th>
          <th>{% trans "Date" %}</th>
        </tr>
      </thead>
      <tbody>
        {% for signed_agreement in user.signedagreement_set.all %}
          <tr>
            <td>
              <a href="{{ signed_agreement.agreement.agreement_pdf.url }}">
                {{ signed_agreement.agreement.name }}
              </a>
            </td>
            <td>{{ signed_agreement.agreement.version }}</td>
            <td>{{ signed_agreement.timestamp|date:"DATE_FORMAT" }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endif %}
{% endblock %}

sandstone/templates/accounts/account_signup.html
{% extends "base.html" %}
{% load i18n mezzanine_tags %}

{% block meta_title %}{{ title }}{% endblock %}
{% block title %}{{ title }}{% endblock %}
{% block body_id %}account{% endblock %}
{% block page_slug %}data-page-slug="account-signup"{% endblock %}

{% block breadcrumb_menu %}
{{ block.super }}
<li>{{ title }}</li>
{% endblock %}

{% block main %}

{% if request.user.is_authenticated %}
    <p>{% trans "You're already logged in. If you'd like to create a new account, you'll need to log out first." %}</p>
{% else %}
    {% errors_for form %}

    <form method="post"{% if form.is_multipart %} enctype="multipart/form-data"{% endif %}>
        <fieldset>
        <legend>{{ title }}</legend>
        <p>{% trans "By creating an account, you'll get access and support to the essential certifications and Firefox OS brand assets needed to build a Firefox OS phone. Your contact information will be shared with our Business Development team and will be used to notify you regarding material changes to the agreements, tools and/or assets provided on this website." %}</p>
        <span class="required-fields">{% trans " = Required Field" %}</span>
        {% fields_for form %}

        <p>{% trans "After you submit your information, we will send you a verification email to activate your account. We will also use your information to communicate with you about Firefox OS and Mozilla initiatives." %}</p>

        <p>{% trans "By proceeding, I agree to the <a href='https://www.mozilla.org/en-US/about/legal.html'>Legal Notice</a> and  <a href='https://www.mozilla.org/en-US/privacy/policies/websites/'>Privacy Notice</a> for Mozilla websites." %}</p>


        <div class="form-actions">
            <button class="signup button button-blue arrow" type="submit" value="{{ title }}"><span>Submit</span></button>
        </div>
        </fieldset>
    </form>
{% endif %}


{% endblock %}